/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/home/mirafra/PycharmProjects/Eda_project/not_gate/not_gate.v:1" *)
module not_gate(a, y);
  (* src = "/home/mirafra/PycharmProjects/Eda_project/not_gate/not_gate.v:2" *)
  input a;
  (* src = "/home/mirafra/PycharmProjects/Eda_project/not_gate/not_gate.v:3" *)
  output y;
  assign y = ~a;
endmodule
