/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/home/mirafra/PycharmProjects/Eda_project/nor_gate/nor_gate.v:1" *)
module nor_gate(a, b, y);
  (* src = "/home/mirafra/PycharmProjects/Eda_project/nor_gate/nor_gate.v:2" *)
  input a;
  (* src = "/home/mirafra/PycharmProjects/Eda_project/nor_gate/nor_gate.v:3" *)
  input b;
  (* src = "/home/mirafra/PycharmProjects/Eda_project/nor_gate/nor_gate.v:4" *)
  output y;
  assign y = ~(b | a);
endmodule
