/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/home/mirafra/PycharmProjects/Eda_project/and_gate/and_gate.v:1" *)
module and_gate(a, b, c);
  (* src = "/home/mirafra/PycharmProjects/Eda_project/and_gate/and_gate.v:2" *)
  input a;
  (* src = "/home/mirafra/PycharmProjects/Eda_project/and_gate/and_gate.v:3" *)
  input b;
  (* src = "/home/mirafra/PycharmProjects/Eda_project/and_gate/and_gate.v:4" *)
  output c;
  assign c = b & a;
endmodule
