/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "adder.v:1" *)
module adder(a, b, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "adder.v:2" *)
  input [3:0] a;
  (* src = "adder.v:3" *)
  input [3:0] b;
  (* src = "adder.v:4" *)
  output [4:0] sum;
  assign _00_ = ~(a[3] ^ b[3]);
  assign _01_ = a[2] & b[2];
  assign _02_ = _01_ & ~(_00_);
  assign _03_ = ~((a[3] & b[3]) | _02_);
  assign _04_ = a[2] ^ b[2];
  assign _05_ = _00_ | ~(_04_);
  assign _06_ = ~(a[1] & b[1]);
  assign _07_ = ~(a[1] ^ b[1]);
  assign _08_ = ~(a[0] & b[0]);
  assign _09_ = ~((_08_ | _07_) & _06_);
  assign _10_ = _05_ | ~(_09_);
  assign sum[4] = ~(_10_ & _03_);
  assign sum[1] = _08_ ^ _07_;
  assign sum[2] = _09_ ^ _04_;
  assign _11_ = ~((_09_ & _04_) | _01_);
  assign sum[3] = _11_ ^ _00_;
  assign sum[0] = a[0] ^ b[0];
endmodule
