/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "xnor_gate.v:1" *)
module xnor_gate(A, B, Y);
  (* src = "xnor_gate.v:2" *)
  input A;
  (* src = "xnor_gate.v:3" *)
  input B;
  (* src = "xnor_gate.v:4" *)
  output Y;
  assign Y = ~(B ^ A);
endmodule
