/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "spi_master.v:1" *)
module spi_master(clk, start, data_in, sclk, mosi, done);
  (* src = "spi_master.v:20" *)
  wire [2:0] _00_;
  (* src = "spi_master.v:20" *)
  wire _01_;
  (* src = "spi_master.v:20" *)
  wire _02_;
  (* src = "spi_master.v:20" *)
  wire _03_;
  (* src = "spi_master.v:20" *)
  wire _04_;
  (* src = "spi_master.v:20" *)
  wire [7:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* init = 3'h0 *)
  (* src = "spi_master.v:11" *)
  reg [2:0] bit_cnt = 3'h0;
  (* init = 1'h0 *)
  (* src = "spi_master.v:12" *)
  reg busy = 1'h0;
  (* src = "spi_master.v:2" *)
  input clk;
  (* src = "spi_master.v:4" *)
  input [7:0] data_in;
  (* src = "spi_master.v:7" *)
  output done;
  reg done;
  (* src = "spi_master.v:6" *)
  output mosi;
  reg mosi;
  (* src = "spi_master.v:5" *)
  output sclk;
  reg sclk;
  (* src = "spi_master.v:10" *)
  reg [7:0] shift_reg;
  (* src = "spi_master.v:3" *)
  input start;
  assign _06_ = sclk ^ busy;
  assign _07_ = start & ~(busy);
  assign _04_ = _06_ & ~(_07_);
  assign _08_ = ~_07_;
  assign _09_ = ~done;
  assign _10_ = ~bit_cnt[2];
  assign _11_ = bit_cnt[1] | bit_cnt[0];
  assign _12_ = _10_ & ~(_11_);
  assign _13_ = ~((_12_ & sclk) | done);
  assign _14_ = busy ? _13_ : _09_;
  assign _02_ = _08_ & ~(_14_);
  assign _15_ = ~bit_cnt[1];
  assign _16_ = bit_cnt[2] ? shift_reg[4] : shift_reg[0];
  assign _17_ = bit_cnt[2] ? shift_reg[6] : shift_reg[2];
  assign _18_ = bit_cnt[1] ? _17_ : _16_;
  assign _19_ = bit_cnt[2] ? shift_reg[5] : shift_reg[1];
  assign _20_ = bit_cnt[2] ? shift_reg[7] : shift_reg[3];
  assign _21_ = bit_cnt[1] ? _20_ : _19_;
  assign _22_ = bit_cnt[0] ? _21_ : _18_;
  assign _23_ = busy ? _22_ : mosi;
  assign _03_ = _07_ ? mosi : _23_;
  assign _24_ = ~((_10_ & _15_) | bit_cnt[0]);
  assign _25_ = sclk ? _24_ : bit_cnt[0];
  assign _26_ = busy ? _25_ : bit_cnt[0];
  assign _00_[0] = _26_ | _07_;
  assign _27_ = ~(bit_cnt[1] ^ bit_cnt[0]);
  assign _28_ = _12_ ? bit_cnt[1] : _27_;
  assign _29_ = sclk ? _28_ : bit_cnt[1];
  assign _30_ = busy ? _29_ : bit_cnt[1];
  assign _00_[1] = _30_ | _07_;
  assign _31_ = ~((bit_cnt[1] | bit_cnt[0]) & bit_cnt[2]);
  assign _32_ = sclk ? _31_ : _10_;
  assign _33_ = busy ? _32_ : _10_;
  assign _00_[2] = ~(_33_ & _08_);
  assign _05_[0] = _07_ ? data_in[0] : shift_reg[0];
  assign _05_[1] = _07_ ? data_in[1] : shift_reg[1];
  assign _05_[2] = _07_ ? data_in[2] : shift_reg[2];
  assign _05_[3] = _07_ ? data_in[3] : shift_reg[3];
  assign _05_[4] = _07_ ? data_in[4] : shift_reg[4];
  assign _05_[5] = _07_ ? data_in[5] : shift_reg[5];
  assign _05_[6] = _07_ ? data_in[6] : shift_reg[6];
  assign _05_[7] = _07_ ? data_in[7] : shift_reg[7];
  assign _34_ = ~(_12_ & sclk);
  assign _01_ = busy ? _34_ : start;
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[0] <= _05_[0];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[1] <= _05_[1];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[2] <= _05_[2];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[3] <= _05_[3];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[4] <= _05_[4];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[5] <= _05_[5];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[6] <= _05_[6];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      shift_reg[7] <= _05_[7];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      bit_cnt[0] <= _00_[0];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      bit_cnt[1] <= _00_[1];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      bit_cnt[2] <= _00_[2];
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      busy <= _01_;
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      mosi <= _03_;
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      done <= _02_;
  (* src = "spi_master.v:20" *)
  always @(posedge clk)
      sclk <= _04_;
endmodule
