TOPLEVEL_LANG = verilog
VERILOG_SOURCES = i2c_master.v
TOPLEVEL = i2c_master
MODULE = test_i2c_master
SIM = icarus
WAVEFORM = i2c_master.vcd
WAVES = 1


include $(shell cocotb-config --makefiles)/Makefile.sim