TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/uart_tx.v
TOPLEVEL = uart_tx
MODULE = test_uart_tx

SIM = icarus

WAVEFORM = results/wave.vcd

include $(shell cocotb-config --makefiles)/Makefile.sim