/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "i2c_master.v:1.1-32.10" *)
module i2c_master(clk, start, addr, data, scl, sda);
  wire _00_;
  (* src = "i2c_master.v:15.13-15.27" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* force_downto = 32'd1 *)
  (* src = "i2c_master.v:24.28-24.39|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _24_;
  (* force_downto = 32'd1 *)
  (* src = "i2c_master.v:0.0-0.0|/usr/bin/../share/yosys/techmap.v:137.23-137.24" *)
  wire _25_;
  (* src = "i2c_master.v:4.17-4.21" *)
  input [6:0] addr;
  wire [6:0] addr;
  (* src = "i2c_master.v:10.15-10.22" *)
  reg [3:0] bit_cnt = 4'h0;
  (* src = "i2c_master.v:12.9-12.13" *)
  reg busy = 1'h0;
  (* src = "i2c_master.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "i2c_master.v:5.17-5.21" *)
  input [7:0] data;
  wire [7:0] data;
  (* src = "i2c_master.v:6.16-6.19" *)
  output scl;
  reg scl = 1'h0;
  (* src = "i2c_master.v:7.16-7.19" *)
  output sda;
  reg sda = 1'h1;
  (* src = "i2c_master.v:11.16-11.25" *)
  wire [15:0] shift_reg;
  (* src = "i2c_master.v:3.11-3.16" *)
  input start;
  wire start;
  assign _24_[0] = ~bit_cnt[0];
  assign _00_ = busy & scl;
  assign _01_ = start & ~(busy);
  assign _02_ = ~(bit_cnt[1] | bit_cnt[0]);
  assign _03_ = bit_cnt[3] | bit_cnt[2];
  assign _04_ = _02_ & ~(_03_);
  assign _23_ = ~(_04_ | scl);
  assign _05_ = ~bit_cnt[2];
  assign _06_ = bit_cnt[0] ? shift_reg[1] : shift_reg[0];
  assign _07_ = bit_cnt[0] ? shift_reg[3] : shift_reg[2];
  assign _08_ = bit_cnt[1] ? _07_ : _06_;
  assign _09_ = bit_cnt[0] ? shift_reg[5] : shift_reg[4];
  assign _10_ = bit_cnt[0] ? shift_reg[7] : shift_reg[6];
  assign _11_ = bit_cnt[1] ? _10_ : _09_;
  assign _12_ = bit_cnt[2] ? _11_ : _08_;
  assign _13_ = shift_reg[9] & bit_cnt[0];
  assign _14_ = bit_cnt[0] ? shift_reg[11] : shift_reg[10];
  assign _15_ = bit_cnt[1] ? _14_ : _13_;
  assign _16_ = bit_cnt[0] ? shift_reg[13] : shift_reg[12];
  assign _17_ = bit_cnt[0] ? shift_reg[15] : shift_reg[14];
  assign _18_ = bit_cnt[1] ? _17_ : _16_;
  assign _19_ = bit_cnt[2] ? _18_ : _15_;
  assign _25_ = bit_cnt[3] ? _19_ : _12_;
  assign _22_ = busy & ~(_04_);
  assign _24_[1] = ~(bit_cnt[1] ^ bit_cnt[0]);
  assign _20_ = bit_cnt[1] | bit_cnt[0];
  assign _24_[2] = _20_ ^ _05_;
  assign _21_ = _05_ & ~(_20_);
  assign _24_[3] = _21_ ^ bit_cnt[3];
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) busy <= 1'h1;
    else busy <= _22_;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) scl <= 1'h0;
    else if (busy) scl <= _23_;
  reg \shift_reg_reg[0] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[0]  <= data[0];
  assign shift_reg[0] = \shift_reg_reg[0] ;
  reg \shift_reg_reg[1] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[1]  <= data[1];
  assign shift_reg[1] = \shift_reg_reg[1] ;
  reg \shift_reg_reg[2] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[2]  <= data[2];
  assign shift_reg[2] = \shift_reg_reg[2] ;
  reg \shift_reg_reg[3] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[3]  <= data[3];
  assign shift_reg[3] = \shift_reg_reg[3] ;
  reg \shift_reg_reg[4] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[4]  <= data[4];
  assign shift_reg[4] = \shift_reg_reg[4] ;
  reg \shift_reg_reg[5] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[5]  <= data[5];
  assign shift_reg[5] = \shift_reg_reg[5] ;
  reg \shift_reg_reg[6] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[6]  <= data[6];
  assign shift_reg[6] = \shift_reg_reg[6] ;
  reg \shift_reg_reg[7] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[7]  <= data[7];
  assign shift_reg[7] = \shift_reg_reg[7] ;
  reg \shift_reg_reg[9] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[9]  <= addr[0];
  assign shift_reg[9] = \shift_reg_reg[9] ;
  reg \shift_reg_reg[10] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[10]  <= addr[1];
  assign shift_reg[10] = \shift_reg_reg[10] ;
  reg \shift_reg_reg[11] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[11]  <= addr[2];
  assign shift_reg[11] = \shift_reg_reg[11] ;
  reg \shift_reg_reg[12] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[12]  <= addr[3];
  assign shift_reg[12] = \shift_reg_reg[12] ;
  reg \shift_reg_reg[13] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[13]  <= addr[4];
  assign shift_reg[13] = \shift_reg_reg[13] ;
  reg \shift_reg_reg[14] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[14]  <= addr[5];
  assign shift_reg[14] = \shift_reg_reg[14] ;
  reg \shift_reg_reg[15] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) \shift_reg_reg[15]  <= addr[6];
  assign shift_reg[15] = \shift_reg_reg[15] ;
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) bit_cnt[0] <= 1'h1;
    else if (_00_) bit_cnt[0] <= _24_[0];
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) bit_cnt[1] <= 1'h1;
    else if (_00_) bit_cnt[1] <= _24_[1];
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) bit_cnt[2] <= 1'h1;
    else if (_00_) bit_cnt[2] <= _24_[2];
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_01_) bit_cnt[3] <= 1'h1;
    else if (_00_) bit_cnt[3] <= _24_[3];
  (* src = "i2c_master.v:14.5-31.8" *)
  always @(posedge clk)
    if (_00_) sda <= _25_;
  assign shift_reg[8] = 1'h0;
endmodule
