TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/design.v
TOPLEVEL = ram
MODULE = test_ram
SIM = icarus
WAVEFORM = waveform.vcd
WAVES = 1


include $(shell cocotb-config --makefiles)/Makefile.sim
