/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module ram(clk_write, address_write, data_write, write_enable, clk_read, address_read, data_read);
  wire [4:0] _00_;
  wire [15:0] _01_;
  wire [15:0] _02_;
  reg [4:0] _03_;
  reg [15:0] _04_;
  wire [15:0] _05_;
  input [4:0] address_read;
  input [4:0] address_write;
  input clk_read;
  input clk_write;
  output [15:0] data_read;
  reg [15:0] data_read;
  input [15:0] data_write;
  input write_enable;
  reg [15:0] memory [31:0];
  assign _01_[0] = write_enable ? data_write[0] : 1'hx;
  assign _01_[1] = write_enable ? data_write[1] : 1'hx;
  assign _01_[2] = write_enable ? data_write[2] : 1'hx;
  assign _01_[3] = write_enable ? data_write[3] : 1'hx;
  assign _01_[4] = write_enable ? data_write[4] : 1'hx;
  assign _01_[5] = write_enable ? data_write[5] : 1'hx;
  assign _01_[6] = write_enable ? data_write[6] : 1'hx;
  assign _01_[7] = write_enable ? data_write[7] : 1'hx;
  assign _01_[8] = write_enable ? data_write[8] : 1'hx;
  assign _01_[9] = write_enable ? data_write[9] : 1'hx;
  assign _01_[10] = write_enable ? data_write[10] : 1'hx;
  assign _01_[11] = write_enable ? data_write[11] : 1'hx;
  assign _01_[12] = write_enable ? data_write[12] : 1'hx;
  assign _01_[13] = write_enable ? data_write[13] : 1'hx;
  assign _01_[14] = write_enable ? data_write[14] : 1'hx;
  assign _01_[15] = write_enable ? data_write[15] : 1'hx;
  assign _00_[0] = write_enable ? address_write[0] : 1'hx;
  assign _00_[1] = write_enable ? address_write[1] : 1'hx;
  assign _00_[2] = write_enable ? address_write[2] : 1'hx;
  assign _00_[3] = write_enable ? address_write[3] : 1'hx;
  assign _00_[4] = write_enable ? address_write[4] : 1'hx;
  always @(posedge clk_read)
      data_read[9] <= _02_[9];
  always @(posedge clk_read)
      data_read[10] <= _02_[10];
  always @(posedge clk_read)
      data_read[11] <= _02_[11];
  always @(posedge clk_read)
      data_read[12] <= _02_[12];
  always @(posedge clk_read)
      data_read[13] <= _02_[13];
  always @(posedge clk_read)
      data_read[14] <= _02_[14];
  always @(posedge clk_read)
      data_read[15] <= _02_[15];
  always @(posedge clk_write)
      _04_[0] <= _01_[0];
  always @(posedge clk_write)
      _04_[1] <= _01_[1];
  always @(posedge clk_write)
      _04_[2] <= _01_[2];
  always @(posedge clk_write)
      _04_[3] <= _01_[3];
  always @(posedge clk_write)
      _04_[4] <= _01_[4];
  always @(posedge clk_write)
      _04_[5] <= _01_[5];
  always @(posedge clk_write)
      _04_[6] <= _01_[6];
  always @(posedge clk_write)
      _04_[7] <= _01_[7];
  always @(posedge clk_write)
      _04_[8] <= _01_[8];
  always @(posedge clk_write)
      _04_[9] <= _01_[9];
  always @(posedge clk_write)
      _04_[10] <= _01_[10];
  always @(posedge clk_write)
      _04_[11] <= _01_[11];
  always @(posedge clk_write)
      _04_[12] <= _01_[12];
  always @(posedge clk_write)
      _04_[13] <= _01_[13];
  always @(posedge clk_write)
      _04_[14] <= _01_[14];
  always @(posedge clk_write)
      _04_[15] <= _01_[15];
  reg _50_;
  always @(posedge clk_write)
      _50_ <= write_enable;
  assign _05_[15] = _50_;
  always @(posedge clk_write)
      _03_[0] <= _00_[0];
  always @(posedge clk_write)
      _03_[1] <= _00_[1];
  always @(posedge clk_write)
      _03_[2] <= _00_[2];
  always @(posedge clk_write)
      _03_[3] <= _00_[3];
  always @(posedge clk_write)
      _03_[4] <= _00_[4];
  always @(posedge clk_read)
      data_read[0] <= _02_[0];
  always @(posedge clk_read)
      data_read[1] <= _02_[1];
  always @(posedge clk_read)
      data_read[2] <= _02_[2];
  always @(posedge clk_read)
      data_read[3] <= _02_[3];
  always @(posedge clk_read)
      data_read[4] <= _02_[4];
  always @(posedge clk_read)
      data_read[5] <= _02_[5];
  always @(posedge clk_read)
      data_read[6] <= _02_[6];
  always @(posedge clk_read)
      data_read[7] <= _02_[7];
  always @(posedge clk_read)
      data_read[8] <= _02_[8];
  \$memrd  #(
    .ABITS(32'd5),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\memory"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd16)
  ) _65_ (
    .ADDR(address_read),
    .CLK(1'hx),
    .DATA(_02_),
    .EN(1'hx)
  );
  \$memwr  #(
    .ABITS(32'd5),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\memory"),
    .PRIORITY(32'd8),
    .WIDTH(32'd16)
  ) _66_ (
    .ADDR(_03_),
    .CLK(1'hx),
    .DATA(_04_),
    .EN({ _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15] })
  );
  assign _05_[14:0] = { _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15], _05_[15] };
endmodule
